export const flattenWineData = (wineData) => ({
  BrandName: wineData.BrandName,
  Name: wineData.Name,
  SQPNI: wineData.SQPNI,
  GTIN: wineData.GTIN,
  EAN: wineData.EAN,
  Country: wineData.Country,
  District: wineData.District,
  Region: wineData.Region,
  WineYear: wineData.WineYear,
  KJ: wineData.Nutrition.KJ,
  Kcal: wineData.Nutrition.Kcal,
  Category: wineData.productInfo.Category,
  Carbs: wineData.Nutrition.Carbs,
  CarbsOfSugar: wineData.Nutrition.CarbsOfSugar,
  Energy: wineData.Nutrition.Energy,
  Organic: wineData.Organic,
  IsPublished: wineData.IsPublished,
  ResidualSugar: wineData.productInfo.ResidualSugar,
  MajorGrape: wineData.productInfo.MajorGrape,
  SecondGrape: wineData.productInfo.SecondGrape,
  ThirdGrape: wineData.productInfo.ThirdGrape,
  FourthGrape: wineData.productInfo.FourthGrape,
  MajorGrapePercentage: wineData.productInfo.MajorGrapePercentage,
  SecondGrapePercentage: wineData.productInfo.SecondGrapePercentage,
  ThirdGrapePercentage: wineData.productInfo.ThirdGrapePercentage,
  FourthGrapePercentage: wineData.productInfo.FourthGrapePercentage,
  MajorGrapeOther: wineData.productInfo.MajorGrapeOther,
  SecondGrapeOther: wineData.productInfo.SecondGrapeOther,
  ThirdGrapeOther: wineData.productInfo.ThirdGrapeOther,
  FourthGrapeOther: wineData.productInfo.FourthGrapeOther,
  Type: wineData.productInfo.Type,
  NetQuantity: wineData.productInfo.NetQuantity,
  Grape: wineData.productInfo.Grape,
  AlcoholVolume: wineData.productInfo.AlcoholVolume,
  Ingredients: wineData.productInfo.Ingredients,
  Sulphites: wineData.productInfo.Sulphites,
  OrganicAcid: wineData.productInfo.OrganicAcid,
  ExpiryDate: wineData.productInfo.ExpiryDate,
  Certificates: wineData.Certificates,
  Sustainability: Array.isArray(wineData.Sustainability)
    ? wineData.Sustainability.join(',')
    : '',
  productionDetails: wineData.productionDetails,
  MajorGrape: wineData.productInfo.MajorGrape || '',
  MajorGrapePercentage: wineData.productInfo.MajorGrapePercentage || 0,

  SecondGrape: wineData.productInfo.SecondGrape || '',
  SecondGrapePercentage: wineData.productInfo.SecondGrapePercentage || 0,

  ThirdGrape: wineData.productInfo.ThirdGrape || '',
  ThirdGrapePercentage: wineData.productInfo.ThirdGrapePercentage || 0,

  FourthGrape: wineData.productInfo.FourthGrape || '',
  FourthGrapePercentage: wineData.productInfo.FourthGrapePercentage || 0,
});
