export const regions = {
  France: [
    'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté',
    'Brittany',
    'Centre-Val de Loire',
    'Corsica',
    'Grand Est',
    'Hauts-de-France',
    'Île-de-France',
    'Normandy',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Pays de la Loire',
    'Provence Alpes Côte d’Azur'
  ],
  England: [
    'London',
    'South East',
    'South West',
    'East of England',
    'West Midlands',
    'East Midlands',
    'Yorkshire and the Humber',
    'North West',
    'North East',
  ],
  Spain: [
    'Aragon',
    'Asturias',
    'Balearic Islands',
    'Basque Country',
    'Canary Islands',
    'Cantabria',
    'Castile and León',
    'Castilla-La Mancha',
    'Catalonia',
    'Extremadura',
    'Galicia',
    'La Rioja',
    'Madrid',
    'Murcia',
    'Navarre',
    'Valencia'
  ],
  Italy: [
    'Aosta Valley', 
    'Piedmont', 
    'Liguria', 
    'Lombardy',
    'Trentino-Alto Adige',
    'Veneto',
    'Friuli Venezia Giulia',
    'Emilia-Romagna',
    'Tuscany',
    'Umbria',
    'Marche',
    'Lazio',
    'Abruzzo',
    'Molise',
    'Campania',
    'Apulia',
    'Basilicata',
    'Calabria',
    'Sicily',
    'Sardinia',
  ],
  Greece: [
    'Attica',
    'Central Greece',
    'Central Macedonia',
    'Crete',
    'Eastern Macedonia and Thrace',
    'Epirus',
    'Ionian Islands',
    'North Aegean',
    'Peloponnese',
    'South Aegean',
    'Thessaly',
    'Western Greece',
    'Western Macedonia'
  ],
  Sweden: [
    'Stockholm County',
    'Uppsala County',
    'Södermanland County',
    'Östergötland County',
    'Jönköping County',
    'Kronoberg County',
    'Kalmar County',
    'Gotland County',
    'Blekinge County',
    'Skåne County',
    'Halland County',
    'Västra Götaland County',
    'Värmland County',
    'Örebro County',
    'Västmanland County',
    'Dalarna County',
    'Gävleborg County',
    'Västernorrland County',
    'Jämtland County',
    'Västerbotten County',
    'Norrbotten County'
  ],
  Austria: [
    'Burgenland',
    'Carinthia',
    'Lower Austria',
    'Upper Austria',
    'Salzburg',
    'Styria',
    'Tyrol',
    'Vorarlberg',
    'Vienna'
  ],
  Belgium: [
    'Brussels-Capital Region',
    'Flanders',
    'Wallonia'
  ],
  Bulgaria: [
    'Blagoevgrad',
    'Burgas',
    'Dobrich',
    'Gabrovo',
    'Haskovo',
    'Kardzhali',
    'Kyustendil',
    'Lovech',
    'Montana',
    'Pazardzhik',
    'Pernik',
    'Pleven',
    'Plovdiv',
    'Razgrad',
    'Ruse',
    'Shumen',
    'Silistra',
    'Sliven',
    'Smolyan',
    'Sofia City',
    'Sofia Province',
    'Stara Zagora',
    'Targovishte',
    'Varna',
    'Veliko Tarnovo',
    'Vidin',
    'Vratsa',
    'Yambol'
  ],
  Croatia: [
    'Istria County',
    'Dalmatia',
    'Zagreb',
    'Bjelovar-Bilogora County',
    'Primorje-Gorski Kotar County',
    'Šibenik-Knin County',
    'Dubrovnik',
    'Slavonia',
    'Zadar',
    'Međimurje County',
    'Split',
    'Krapina-Zagorje County',
    'Kvarner Gulf',
    'Lika',
    'Sisak-Moslavina County',
    'Split-Dalmatia County',
    'Varaždin County',
    'Central Croatia',
  ],
  Cyprus: [
    'Nicosia',
    'Limassol',
    'Larnaca',
    'Paphos',
    'Famagusta',
    'Kyrenia',
  ],
  Czech: [
    'Prague',
    'Central Bohemian',
    'South Bohemian',
    'Plzeň',
    'Karlovy Vary',
    'Ústí nad Labem',
    'Liberec',
    'Hradec Králové',
    'Pardubice',
    'Olomouc',
    'Moravian-Silesian',
    'South Moravian',
    'Zlín',
    'Vysočina',
  ],
  Denmark: [
    'Capital Region',
    'Zealand',
    'Southern Denmark',
    'Central Denmark',
    'North Denmark'
  ],
  Estonia: [
    'Harju County',
    'Hiiu County',
    'Ida-Viru County',
    'Jõgeva County',
    'Järva County',
    'Lääne County',
    'Lääne-Viru County',
    'Põlva County',
    'Pärnu County',
    'Rapla County',
    'Saare County',
    'Tartu County',
    'Valga County',
    'Viljandi County',
    'Võru County'
  ],
  Finland: [
    'Åland',
    'South Karelia',
    'Southern Ostrobothnia',
    'South Savo',
    'Kainuu',
    'Tavastia Proper',
    'Central Ostrobothnia',
    'Central Finland',
    'Kymenlaakso',
    'Lapland',
    'Pirkanmaa',
    'Ostrobothnia',
    'North Karelia',
    'North Ostrobothnia',
    'North Savo',
    'Päijät-Häme',
    'Satakunta',
    'Uusimaa',
    'Southwest Finland'
  ],
  Germany: [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Western Pomerania',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia'
  ],
  Hungary: [
    'Bács-Kiskun',
    'Baranya',
    'Békés',
    'Borsod-Abaúj-Zemplén',
    'Csongrád-Csanád',
    'Fejér',
    'Győr-Moson-Sopron',
    'Hajdú-Bihar',
    'Heves',
    'Jász-Nagykun-Szolnok',
    'Komárom-Esztergom',
    'Nógrád',
    'Pest',
    'Somogy',
    'Szabolcs-Szatmár-Bereg',
    'Tolna',
    'Vas',
    'Veszprém',
    'Zala',
    'Budapest',
  ],
  Ireland: [
    'Carlow',
    'Cavan',
    'Clare',
    'Cork',
    'Donegal',
    'Dublin',
    'Galway',
    'Kerry',
    'Kildare',
    'Kilkenny',
    'Laois',
    'Leitrim',
    'Limerick',
    'Longford',
    'Louth',
    'Mayo',
    'Meath',
    'Monaghan',
    'Offaly',
    'Roscommon',
    'Sligo',
    'Tipperary',
    'Waterford',
    'Westmeath',
    'Wexford',
    'Wicklow',
  ],
  Latvia: [
    'Kurzeme',
    'Latgale',
    'Riga Region',
    'Vidzeme',
    'Zemgale',
  ],
  Lithuania: [
    'Alytus County',
    'Kaunas County',
    'Klaipėda County',
    'Marijampolė County',
    'Panevėžys County',
    'Šiauliai County',
    'Tauragė County',
    'Telšiai County',
    'Utena County',
    'Vilnius County',
  ],
  Luxembourg: [
    'Capellen',
    'Clervaux',
    'Diekirch',
    'Echternach',
    'Esch-sur-Alzette',
    'Grevenmacher',
    'Luxembourg',
    'Mersch',
    'Redange',
    'Remich',
    'Vianden',
    'Wiltz',
  ],
  Malta: [
    'Central Region',
    'Gozo Region',
    'Northern Region',
    'South Eastern Region',
    'Southern Region',
  ],
  Netherlands: [
    'Drenthe',
    'Flevoland',
    'Friesland',
    'Gelderland',
    'Groningen',
    'Limburg',
    'North Brabant',
    'North Holland',
    'Overijssel',
    'South Holland',
    'Utrecht',
    'Zeeland',
  ],
  Poland: [
    'Greater Poland',
    'Kuyavian-Pomeranian',
    'Lesser Poland',
    'Łódź',
    'Lower Silesian',
    'Lublin',
    'Lubusz',
    'Masovian',
    'Opole',
    'Podkarpackie',
    'Podlaskie',
    'Pomeranian',
    'Silesian',
    'Świętokrzyskie',
    'Warmian-Masurian',
    'West Pomeranian',
  ],
  Portugal: [
    'Northern Portugal',
    'Centre',
    'Lisbon Metropolitan Area',
    'Alentejo',
    'Algarve',
    'Azores',
    'Madeira',
  ],
  Romania: [
    'North-West',
    'Center',
    'North-East',
    'South-East',
    'South-Muntenia',
    'Bucharest-Ilfov',
    'South-West Oltenia',
    'West',
  ],
  Slovakia: [
    'Bratislava Region',
    'Trnava Region',
    'Trenčín Region',
    'Nitra Region',
    'Žilina Region',
    'Banská Bystrica Region',
    'Prešov Region',
    'Košice Region',
  ],
  Slovenia: [
    'Pomurska',
    'Podravska',
    'Koroška',
    'Savinjska',
    'Zasavska',
    'Posavska',
    'Jugovzhodna Slovenija',
    'Osrednjeslovenska',
    'Gorenjska',
    'Primorsko-notranjska',
    'Goriška',
    'Obalno-kraška',
  ]
};